// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDq5yb34lnI1JsYrhzyvFKze8Df6LLtUE',
    appId: '1:816085659928:web:68cc744483a2e563ed6e6d',
    messagingSenderId: '816085659928',
    projectId: 'eldercareapp-22ad3',
    authDomain: 'eldercareapp-22ad3.firebaseapp.com',
    storageBucket: 'eldercareapp-22ad3.firebasestorage.app',
    measurementId: 'G-4EET8GP01D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4fgj-ohzGVVQEDiscSi0CmtvUGKCKqNc',
    appId: '1:816085659928:android:673980070ce20299ed6e6d',
    messagingSenderId: '816085659928',
    projectId: 'eldercareapp-22ad3',
    storageBucket: 'eldercareapp-22ad3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc3z8I9PvQd2nkNWwie2dYR4vLJEhPb9s',
    appId: '1:816085659928:ios:e9b9d0282511c4f3ed6e6d',
    messagingSenderId: '816085659928',
    projectId: 'eldercareapp-22ad3',
    storageBucket: 'eldercareapp-22ad3.firebasestorage.app',
    iosBundleId: 'com.example.elderCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc3z8I9PvQd2nkNWwie2dYR4vLJEhPb9s',
    appId: '1:816085659928:ios:e9b9d0282511c4f3ed6e6d',
    messagingSenderId: '816085659928',
    projectId: 'eldercareapp-22ad3',
    storageBucket: 'eldercareapp-22ad3.firebasestorage.app',
    iosBundleId: 'com.example.elderCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDq5yb34lnI1JsYrhzyvFKze8Df6LLtUE',
    appId: '1:816085659928:web:d55dfe8bb743d851ed6e6d',
    messagingSenderId: '816085659928',
    projectId: 'eldercareapp-22ad3',
    authDomain: 'eldercareapp-22ad3.firebaseapp.com',
    storageBucket: 'eldercareapp-22ad3.firebasestorage.app',
    measurementId: 'G-63WWYQZ4Y2',
  );

}